language: node_js
node_js:
  - "5"
services:
  - mongodb
env:
  global:
    - MONGODB_VERSION=3.2.5
before_install:
  - npm i codecov
script:
  - npm t
  - npm run coverage
after_success:
  - npm run report
notifications:
  email: false
